"""add desktop orm models

Revision ID: 3e1f847a7eca
Revises: 5720548b7f0d
Create Date: 2026-05-01 19:29:46.077677
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '3e1f847a7eca'
down_revision: Union[str, None] = '5720548b7f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('med_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_folder', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), server_default='', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('vat', sa.Float(), server_default='0', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['med_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('med_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_med_services_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_med_services_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('role', sa.Enum('operator', 'cashier', 'admin', name='role'), server_default='operator', nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=False),
    sa.Column('contract_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('birth_history_number', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('patient_birth_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('patient_reg_address', sa.String(), nullable=False),
    sa.Column('patient_live_address', sa.String(), nullable=False),
    sa.Column('patient_phone', sa.String(), nullable=False),
    sa.Column('patient_passport_issued_by', sa.String(), nullable=False),
    sa.Column('patient_passport_issued_code', sa.String(), nullable=False),
    sa.Column('patient_passport_series', sa.String(), nullable=False),
    sa.Column('patient_passport_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delegate_name', sa.String(), nullable=True),
    sa.Column('delegate_birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delegate_reg_address', sa.String(), nullable=True),
    sa.Column('delegate_live_address', sa.String(), nullable=True),
    sa.Column('delegate_phone', sa.String(), nullable=True),
    sa.Column('delegate_passport_issued_by', sa.String(), nullable=True),
    sa.Column('delegate_passport_issued_code', sa.String(), nullable=True),
    sa.Column('delegate_passport_series', sa.String(), nullable=True),
    sa.Column('delegate_passport_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inpatient_treatment', sa.Boolean(), nullable=True),
    sa.Column('childbirth', sa.Boolean(), nullable=True),
    sa.Column('prepay_inpatient_treatment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prepay_childbirth', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('service_payed', sa.Boolean(), nullable=True),
    sa.Column('service_insurance', sa.Boolean(), nullable=True),
    sa.Column('service_insurance_number', sa.String(), nullable=True),
    sa.Column('discharged', sa.Boolean(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_contract_number'), ['contract_number'], unique=True)

    op.create_table('acts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acts_number'), ['number'], unique=True)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('posted', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('unposted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unposted_by_id', sa.Integer(), nullable=True),
    sa.Column('unpost_reason', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unposted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('act_med_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('med_service_id', sa.Integer(), nullable=False),
    sa.Column('current_code', sa.String(), nullable=True),
    sa.Column('current_name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), server_default='шт', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['med_service_id'], ['med_services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('act_med_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_act_med_services_current_code'), ['current_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_act_med_services_current_name'), ['current_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('act_med_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_act_med_services_current_name'))
        batch_op.drop_index(batch_op.f('ix_act_med_services_current_code'))

    op.drop_table('act_med_services')
    op.drop_table('payments')
    with op.batch_alter_table('acts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acts_number'))

    op.drop_table('acts')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_contract_number'))

    op.drop_table('contracts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('med_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_med_services_name'))
        batch_op.drop_index(batch_op.f('ix_med_services_code'))

    op.drop_table('med_services')
    # ### end Alembic commands ###
